# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qhb21126/Desktop/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/General_Filter/ip/General_Filter_xbar_6/General_Filter_xbar_6.xci
# IP: The module: 'General_Filter_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qhb21126/Desktop/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_xbar_6/General_Filter_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_xbar_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/qhb21126/Desktop/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/General_Filter/ip/General_Filter_xbar_6/General_Filter_xbar_6.xci
# IP: The module: 'General_Filter_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qhb21126/Desktop/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_xbar_6/General_Filter_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_xbar_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
