# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/Filter/ip/Filter_filter_0_0/Filter_filter_0_0.xci
# IP: The module: 'Filter_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/filter_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i0 || ORIG_REF_NAME==filter_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i1/filter_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i1 || ORIG_REF_NAME==filter_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i2/filter_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i2 || ORIG_REF_NAME==filter_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i3/filter_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i3 || ORIG_REF_NAME==filter_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i4/filter_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i4 || ORIG_REF_NAME==filter_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i5/filter_c_addsub_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i5 || ORIG_REF_NAME==filter_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i6/filter_c_addsub_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i6 || ORIG_REF_NAME==filter_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i7/filter_c_addsub_v12_0_i7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i7 || ORIG_REF_NAME==filter_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i8/filter_c_addsub_v12_0_i8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i8 || ORIG_REF_NAME==filter_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i9/filter_c_addsub_v12_0_i9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i9 || ORIG_REF_NAME==filter_c_addsub_v12_0_i9} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/filter_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==filter_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/filter_div_gen_v5_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_div_gen_v5_1_i0 || ORIG_REF_NAME==filter_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/filter_fifo_generator_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i0 || ORIG_REF_NAME==filter_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i1/filter_fifo_generator_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i1 || ORIG_REF_NAME==filter_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i0/filter_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i0 || ORIG_REF_NAME==filter_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i1/filter_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i1 || ORIG_REF_NAME==filter_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i2/filter_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i2 || ORIG_REF_NAME==filter_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i3/filter_mult_gen_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i3 || ORIG_REF_NAME==filter_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i4/filter_mult_gen_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i4 || ORIG_REF_NAME==filter_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/filter_fifo_generator_i0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i0 || ORIG_REF_NAME==filter_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i1/filter_fifo_generator_i1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i1 || ORIG_REF_NAME==filter_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/constrs/filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'Filter_filter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/Filter/ip/Filter_filter_0_0/Filter_filter_0_0.xci
# IP: The module: 'Filter_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/filter_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i0 || ORIG_REF_NAME==filter_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i1/filter_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i1 || ORIG_REF_NAME==filter_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i2/filter_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i2 || ORIG_REF_NAME==filter_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i3/filter_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i3 || ORIG_REF_NAME==filter_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i4/filter_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i4 || ORIG_REF_NAME==filter_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i5/filter_c_addsub_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i5 || ORIG_REF_NAME==filter_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i6/filter_c_addsub_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i6 || ORIG_REF_NAME==filter_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i7/filter_c_addsub_v12_0_i7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i7 || ORIG_REF_NAME==filter_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i8/filter_c_addsub_v12_0_i8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i8 || ORIG_REF_NAME==filter_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i9/filter_c_addsub_v12_0_i9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_addsub_v12_0_i9 || ORIG_REF_NAME==filter_c_addsub_v12_0_i9} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/filter_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==filter_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/filter_div_gen_v5_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_div_gen_v5_1_i0 || ORIG_REF_NAME==filter_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/filter_fifo_generator_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i0 || ORIG_REF_NAME==filter_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i1/filter_fifo_generator_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i1 || ORIG_REF_NAME==filter_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i0/filter_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i0 || ORIG_REF_NAME==filter_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i1/filter_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i1 || ORIG_REF_NAME==filter_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i2/filter_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i2 || ORIG_REF_NAME==filter_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i3/filter_mult_gen_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i3 || ORIG_REF_NAME==filter_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i4/filter_mult_gen_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_mult_gen_v12_0_i4 || ORIG_REF_NAME==filter_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/filter_fifo_generator_i0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i0 || ORIG_REF_NAME==filter_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i1/filter_fifo_generator_i1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_fifo_generator_i1 || ORIG_REF_NAME==filter_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/constrs/filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'Filter_filter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
