# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/General_Filter/General_Filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter || ORIG_REF_NAME==General_Filter} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_processing_system7_0_0/General_Filter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_processing_system7_0_0 || ORIG_REF_NAME==General_Filter_processing_system7_0_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_general_filter_0_0/General_Filter_general_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_general_filter_0_0 || ORIG_REF_NAME==General_Filter_general_filter_0_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_axi_dma_0/General_Filter_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_axi_dma_0 || ORIG_REF_NAME==General_Filter_axi_dma_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_xbar_0/General_Filter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_xbar_0 || ORIG_REF_NAME==General_Filter_xbar_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_axi_mem_intercon_0/General_Filter_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_axi_mem_intercon_0 || ORIG_REF_NAME==General_Filter_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_rst_ps7_0_100M_0/General_Filter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_rst_ps7_0_100M_0 || ORIG_REF_NAME==General_Filter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_xbar_1/General_Filter_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_xbar_1 || ORIG_REF_NAME==General_Filter_xbar_1} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_ps7_0_axi_periph_0/General_Filter_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_ps7_0_axi_periph_0 || ORIG_REF_NAME==General_Filter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_us_0 || ORIG_REF_NAME==General_Filter_auto_us_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_pc_0/General_Filter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_pc_0 || ORIG_REF_NAME==General_Filter_auto_pc_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_pc_1/General_Filter_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_pc_1 || ORIG_REF_NAME==General_Filter_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/General_Filter_ooc.xdc
