# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/General_Filter/General_Filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter || ORIG_REF_NAME==General_Filter} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_processing_system7_0_2/General_Filter_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_processing_system7_0_2 || ORIG_REF_NAME==General_Filter_processing_system7_0_2} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_general_filter_0_3/General_Filter_general_filter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_general_filter_0_3 || ORIG_REF_NAME==General_Filter_general_filter_0_3} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_axi_dma_3/General_Filter_axi_dma_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_axi_dma_3 || ORIG_REF_NAME==General_Filter_axi_dma_3} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_xbar_6/General_Filter_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_xbar_6 || ORIG_REF_NAME==General_Filter_xbar_6} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_us_df_0/General_Filter_auto_us_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_us_df_0 || ORIG_REF_NAME==General_Filter_auto_us_df_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_s01_data_fifo_0/General_Filter_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_s01_data_fifo_0 || ORIG_REF_NAME==General_Filter_s01_data_fifo_0} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_us_df_1/General_Filter_auto_us_df_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_us_df_1 || ORIG_REF_NAME==General_Filter_auto_us_df_1} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_m00_data_fifo_4/General_Filter_m00_data_fifo_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_m00_data_fifo_4 || ORIG_REF_NAME==General_Filter_m00_data_fifo_4} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_pc_2/General_Filter_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_pc_2 || ORIG_REF_NAME==General_Filter_auto_pc_2} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_m01_data_fifo_4/General_Filter_m01_data_fifo_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_m01_data_fifo_4 || ORIG_REF_NAME==General_Filter_m01_data_fifo_4} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_axi_mem_intercon_3/General_Filter_axi_mem_intercon_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_axi_mem_intercon_3 || ORIG_REF_NAME==General_Filter_axi_mem_intercon_3} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_rst_ps7_0_100M_3/General_Filter_rst_ps7_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_rst_ps7_0_100M_3 || ORIG_REF_NAME==General_Filter_rst_ps7_0_100M_3} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_xbar_7/General_Filter_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_xbar_7 || ORIG_REF_NAME==General_Filter_xbar_7} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_s00_data_fifo_5/General_Filter_s00_data_fifo_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_s00_data_fifo_5 || ORIG_REF_NAME==General_Filter_s00_data_fifo_5} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_auto_pc_3/General_Filter_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_auto_pc_3 || ORIG_REF_NAME==General_Filter_auto_pc_3} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_m00_data_fifo_5/General_Filter_m00_data_fifo_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_m00_data_fifo_5 || ORIG_REF_NAME==General_Filter_m00_data_fifo_5} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_m01_data_fifo_5/General_Filter_m01_data_fifo_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_m01_data_fifo_5 || ORIG_REF_NAME==General_Filter_m01_data_fifo_5} -quiet] -quiet

# IP: bd/General_Filter/ip/General_Filter_ps7_0_axi_periph_4/General_Filter_ps7_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==General_Filter_ps7_0_axi_periph_4 || ORIG_REF_NAME==General_Filter_ps7_0_axi_periph_4} -quiet] -quiet

# XDC: c:/Users/qhb21126/Desktop/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/General_Filter_ooc.xdc
