# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dsb21132/project_simple_add/project_simple_add.srcs/sources_1/bd/design_1/ip/design_1_simple_add_0_0/design_1_simple_add_0_0.xci
# IP: The module: 'design_1_simple_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dsb21132/project_simple_add/project_simple_add.gen/sources_1/bd/design_1/ip/design_1_simple_add_0_0/simple_add_c_addsub_v12_0_i0/simple_add_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_add_c_addsub_v12_0_i0 || ORIG_REF_NAME==simple_add_c_addsub_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/dsb21132/project_simple_add/project_simple_add.gen/sources_1/bd/design_1/ip/design_1_simple_add_0_0/constrs/simple_add.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_simple_add_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/dsb21132/project_simple_add/project_simple_add.srcs/sources_1/bd/design_1/ip/design_1_simple_add_0_0/design_1_simple_add_0_0.xci
# IP: The module: 'design_1_simple_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dsb21132/project_simple_add/project_simple_add.gen/sources_1/bd/design_1/ip/design_1_simple_add_0_0/simple_add_c_addsub_v12_0_i0/simple_add_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_add_c_addsub_v12_0_i0 || ORIG_REF_NAME==simple_add_c_addsub_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/dsb21132/project_simple_add/project_simple_add.gen/sources_1/bd/design_1/ip/design_1_simple_add_0_0/constrs/simple_add.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_simple_add_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
