#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : Filter.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Apr 26 11:17:59 +0100 2024
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Filter.sh [-help]
# usage: Filter.sh [-lib_map_path]
# usage: Filter.sh [-noclean_files]
# usage: Filter.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Filter.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 axi_utils_v2_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 floating_point_v7_0_18 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_17 fifo_generator_v13_2_5 lib_pkg_v1_0_2 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_24 axi_sg_v4_1_13 axi_dma_v7_1_23 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 proc_sys_reset_v5_0_13 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Filter.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Filter/ip/Filter_processing_system7_0_0/sim/Filter_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i0/sim/filter_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i1/sim/filter_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i2/sim/filter_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i3/sim/filter_c_addsub_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i4/sim/filter_c_addsub_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i5/sim/filter_c_addsub_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i6/sim/filter_c_addsub_v12_0_i6.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i7/sim/filter_c_addsub_v12_0_i7.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i8/sim/filter_c_addsub_v12_0_i8.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_addsub_v12_0_i9/sim/filter_c_addsub_v12_0_i9.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_c_counter_binary_v12_0_i0/sim/filter_c_counter_binary_v12_0_i0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_18 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_div_gen_v5_1_i0/sim/filter_div_gen_v5_1_i0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i0/sim/filter_fifo_generator_i0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_fifo_generator_i1/sim/filter_fifo_generator_i1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i0/sim/filter_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i1/sim/filter_mult_gen_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i2/sim/filter_mult_gen_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i3/sim/filter_mult_gen_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/filter_mult_gen_v12_0_i4/sim/filter_mult_gen_v12_0_i4.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/srl17e.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/srl33e.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/filter_entity_declarations.vhd" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/filter.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/filter_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/synth_reg.v" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl/convert_type.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_filter_0_0/sim/Filter_filter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_23 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/89d8/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_axi_dma_0/sim/Filter_axi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Filter/ip/Filter_xbar_0/sim/Filter_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/ip/Filter_rst_ps7_0_100M_0/sim/Filter_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Filter/ip/Filter_xbar_1/sim/Filter_xbar_1.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_s00_regslice_3/sim/Filter_s00_regslice_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../VivadoProject.gen/sources_1/bd/Filter/ipshared/9756/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Filter/ip/Filter_auto_us_df_0/sim/Filter_auto_us_df_0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_s01_regslice_0/sim/Filter_s01_regslice_0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_s01_data_fifo_0/sim/Filter_s01_data_fifo_0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m00_data_fifo_3/sim/Filter_m00_data_fifo_3.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m00_regslice_3/sim/Filter_m00_regslice_3.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_auto_pc_0/sim/Filter_auto_pc_0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_s00_regslice_4/sim/Filter_s00_regslice_4.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_s00_data_fifo_4/sim/Filter_s00_data_fifo_4.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_auto_pc_1/sim/Filter_auto_pc_1.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m00_data_fifo_4/sim/Filter_m00_data_fifo_4.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m00_regslice_4/sim/Filter_m00_regslice_4.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m01_data_fifo_0/sim/Filter_m01_data_fifo_0.v" \
    "$ref_dir/../../../bd/Filter/ip/Filter_m01_regslice_0/sim/Filter_m01_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Filter/sim/Filter.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Filter xil_defaultlib.glbl -o Filter_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Filter_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Filter.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Filter_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Filter_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Filter.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Filter.sh [-help]\n\
Usage: Filter.sh [-lib_map_path]\n\
Usage: Filter.sh [-reset_run]\n\
Usage: Filter.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
