# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0.xci
# IP: The module: 'General_Filter_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.srcs/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0.xci
# IP: The module: 'General_Filter_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/qhb21126/Documents/MATLAB/GIT/image_filtering_pynq/VivadoProject/VivadoProject.gen/sources_1/bd/General_Filter/ip/General_Filter_auto_us_0/General_Filter_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'General_Filter_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
